spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/store?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 2MB #默认上传为1MB
      max-request-size: 5MB #请求文件最大的大小，包含文件最大大小

#定义mapper对应的xml文件的路径
mybatis:
  mapper-locations: classpath:mapper/*.xml
