spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/store?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 5MB #默认上传为1MB 若上传文件超过该容量会报error，即设定的上传大小要小于该值,否则捕获不到自定义文件大小异常
      max-request-size: 10MB #请求文件最大的大小，包含文件最大大小

#定义mapper对应的xml文件的路径
mybatis:
  mapper-locations: classpath:mapper/*.xml
#定义收货条数最大值
address:
  max-count: 20
